configurations:
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkRadioButtonTesting/
        - Sources/SparkRadioButtonSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoMockable.stencil
    output: Sources/SparkRadioButtonTesting/Generated/AutoMockable.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkRadioButton]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkRadioButtonTesting/
        - Sources/SparkRadioButtonSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoMockTest.stencil
    output: Sources/SparkRadioButtonTesting/Generated/AutoMockTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkRadioButton]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkRadioButtonTesting/
        - Sources/SparkRadioButtonSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoPublisherTest.stencil
    output: Sources/SparkRadioButtonTesting/Generated/AutoPublisherTest.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkRadioButton]
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/SparkRadioButtonTesting/
        - Sources/SparkRadioButtonSnapshotTesting/
    templates:
      - ../spark-ios-common/.sourcery/template/SparkAutoViewModelStub.stencil
    output: Sources/SparkRadioButtonTesting/Generated/AutoViewModelStub.generated.swift
    args:
      autoMockableImports: [Combine, SparkTheming]
      autoMockableSPIImports: [SparkCommon, SparkCommonTesting, SparkThemingTesting]
      autoMockableTestableImports: [SparkRadioButton]
